name: Build

on: 
  push: 
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout SDK
      uses: actions/checkout@v4
      with: 
        repository: 3DiVi/open-source-face-sdk
        path: open-source-face-sdk
        
    - name: Setup
      run: |
          pip install gdown
          choco install wget

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build SDK
      working-directory: open-source-face-sdk
      run: |
          Add-Content sdk\scripts\windows\make_project.ps1 "msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj"
          cd sdk && .\scripts\windows\make_project.ps1

    - name: Rename
      working-directory: open-source-face-sdk
      run: Rename-Item -Path sdk\build\make-install\bin -NewName dll

    - name: Move libs
      working-directory: open-source-face-sdk
      run: Move-Item -Path sdk\build\make-install\dll\*.lib -Destination sdk\build\make-install\lib

    - name: Clean
      working-directory: open-source-face-sdk
      run: |
          Remove-Item sdk\build\make-install\dll\*.exe
          Remove-Item sdk\build\make-install\dll\*.py
          Remove-Item -Path sdk\build\make-install\python_api -Recurse -Force

    - name: Current directory
      run: dir

    - name: Checkout NeuralNetworksBackend
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Current directory
      run: dir

    - name: Copy
      working-directory: open-source-face-sdk
      run: Copy-Item -Path sdk\build\make-install\* -Destination ${{ github.workspace }}\sdk -Recurse
  
    - name: Current directory
      run: dir
    
    - name: Get WebFramework
      uses: actions/checkout@v4
      with:
        repository: https://github.com/LazyPanda07/WebFramework.git
        ref: build
        path: WebFrameworkLibrary
        submodules: true
        
    - name: Setup WebFramework
      run: |
          cd WebFrameworkLibrary
          msbuild /p:Configuration=ProductionRelease /p:Platform=x64 WebFramework.sln
          echo "WebFrameworkSDK=${{ github.workspace }}\WebFrameworkLibrary\build\ProductionRelease-x64" >> $Env:GITHUB_ENV

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform=x64 NeuralNetworksBackend.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NeuralNetworksBackend
        path: bin\Release-x64\NeuralNetworksBackend
