name: Build

on: 
  push: 
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
       lfs: true

    - name: Checkout SDK
      uses: actions/checkout@v4
      with: 
        repository: 3DiVi/open-source-face-sdk
        path: open-source-face-sdk
        
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3

    - name: Setup
      run: |
          conda config --add pkgs_dirs ${{ github.workspace }}\conda
          pip install gdown
          choco install wget
          conda install cudatoolkit=10.1
          conda install -c conda-forge cudnn=7.6.5.32

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build SDK
      working-directory: open-source-face-sdk
      run: |
          Add-Content sdk\scripts\windows\make_project.ps1 "msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj"
          cd sdk && .\scripts\windows\make_project.ps1

    - name: Rename
      working-directory: open-source-face-sdk
      run: Rename-Item -Path sdk\build\make-install\bin -NewName dll

    - name: Move libs
      working-directory: open-source-face-sdk
      run: Move-Item -Path sdk\build\make-install\dll\*.lib -Destination sdk\build\make-install\lib

    - name: Clean
      working-directory: open-source-face-sdk
      run: |
          Remove-Item sdk\build\make-install\dll\*.exe
          Remove-Item sdk\build\make-install\dll\*.py
          Remove-Item -Path sdk\build\make-install\python_api -Recurse -Force
          
    - name: Copy SDK
      working-directory: open-source-face-sdk
      run: Copy-Item -Path sdk\build\make-install\* -Destination ${{ github.workspace }}\NeuralNetworksBackend\sdk -Recurse -Force

    - name: Checkout JSON
      uses: actions/checkout@v4
      with:
        repository: LazyPanda07/JSON
        path: JSON

    - name: Build JSON
      run: |
          cd JSON
          msbuild /p:Configuration=ProductionRelease /p:Platform=x64 JSON.vcxproj

    - name: Checkout ThreadPool
      uses: actions/checkout@v4
      with:
        repository: LazyPanda07/ThreadPool
        path: ThreadPool

    - name: Build ThreadPool
      run: |
          cd ThreadPool
          msbuild /p:Configuration=Release /p:Platform=x64 ThreadPool.vcxproj

    - name: Checkout WebFramework
      uses: actions/checkout@v4
      with: 
        repository: LazyPanda07/WebFramework
        path: WebFrameworkLibrary
        submodules: recursive
        ref: build

    - name: Copy dependencies
      shell: bash
      run: |
          cp -r -f JSON/bin/ProductionRelease-x64/JSON/* WebFrameworkLibrary/Localization/dependencies/JSON/libs/ProductionRelease-x64
          cp -r -f ThreadPool/bin/Release-x64/ThreadPool/* WebFrameworkLibrary/FileManager/dependencies/ThreadPool/libs/release

    - name: Build WebFramework
      shell: cmd
      run: |
          cd WebFrameworkLibrary
          msbuild /p:Configuration=ProductionRelease /p:Platform=x64 WebFramework.sln

    - name: Build
      run: |
          Get-ChildItem -Path ${{ github.workspace }}\conda\cudatoolkit-10.1.243-h74a9793_0 -Recurse
          Get-ChildItem -Path ${{ github.workspace }}\conda\cudnn-7.6.5.32-h36d860d_1 -Recurse
          msbuild /p:Configuration=Release /p:Platform=x64 /p:WebFrameworkSDK=${{ github.workspace }}\WebFrameworkLibrary\build\ProductionRelease-x64\ NeuralNetworksBackend.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NeuralNetworksBackend
        path: bin\Release-x64\NeuralNetworksBackend
