name: Build

on: 
  push: 
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
       lfs: true

    - name: Checkout SDK
      uses: actions/checkout@v4
      with: 
        repository: 3DiVi/open-source-face-sdk
        path: open-source-face-sdk
        
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3

    - name: Setup
      run: |
          pip install gdown
          choco install wget
          conda install cudatoolkit=10.1
          conda install -c conda-forge cudnn=7.6.5.32

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build SDK
      working-directory: open-source-face-sdk
      run: |
          Add-Content sdk\scripts\windows\make_project.ps1 "msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj"
          cd sdk && .\scripts\windows\make_project.ps1

    - name: Rename
      working-directory: open-source-face-sdk
      run: Rename-Item -Path sdk\build\make-install\bin -NewName dll

    - name: Move libs
      working-directory: open-source-face-sdk
      run: Move-Item -Path sdk\build\make-install\dll\*.lib -Destination sdk\build\make-install\lib

    - name: Clean
      working-directory: open-source-face-sdk
      run: |
          Remove-Item sdk\build\make-install\dll\*.exe
          Remove-Item sdk\build\make-install\dll\*.py
          Remove-Item -Path sdk\build\make-install\python_api -Recurse -Force
          
    - name: Copy
      working-directory: open-source-face-sdk
      run: Copy-Item -Path sdk\build\make-install\* -Destination ${{ github.workspace }}\NeuralNetworksBackend\sdk -Recurse -Force
  
    - name: Get WebFramework
      shell: bash
      run: |
          wget https://github.com/LazyPanda07/WebFramework/releases/download/v2.4/build.zip
          unzip build.zip -d WebFrameworkLibrary
          
    - name: Build
      run: |
          echo "WebFrameworkSDK="${{ github.workspace }}\WebFrameworkLibrary\ProductionRelease-x64\"" >> $Env:GITHUB_ENV
          msbuild /p:Configuration=Release /p:Platform=x64 NeuralNetworksBackend.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NeuralNetworksBackend
        path: bin\Release-x64\NeuralNetworksBackend
