name: Get SDK

on: workflow_dispatch

jobs:
  sdk:
    runs-on: windows-latest
    steps:
    - name: Checkout SDK
      uses: actions/checkout@v4
      with: 
        repository: 3DiVi/open-source-face-sdk
        ref: main

    - name: Setup
      run: |
          pip install gdown
          choco install wget

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build SDK
      run: |
          Add-Content sdk\scripts\windows\make_project.ps1 "msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj"
          cd sdk && .\scripts\windows\make_project.ps1

    - name: Move libs
      run: Move-Item -Path sdk\build\make-install\bin\*.lib -Destination sdk\build\make-install\lib

    - name: Clean
      run: |
          Remove-Item sdk\build\make-install\bin\*.exe
          Remove-Item sdk\build\make-install\bin\*.py
          Remove-Item -Path sdk\build\make-install\python_api -Recurse -Force
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sdk
        path: sdk/build/make-install/
      