name: Get SDK binaries

on: workflow_dispatch

jobs:
  build_sdk:
    runs-on: windows-latest
    steps:
    - name: Clone SDK
      uses: actions/checkout@v4
      with: 
        repository: 3DiVi/open-source-face-sdk
        ref: main

    - name: Setup
      run: pip install gdown

    - name: Build SDK
      run: |
          $PSVersionTable
          Add-Content sdk\scripts\windows\make_project.ps1 "msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj"
          cd sdk && .\scripts\windows\make_project.ps1

    - name: Clean
      run: |
          Remove-Item sdk\build\make-install\bin\*.exe
          Remove-Item sdk\build\make-install\bin\*.py
          Remove-Item sdk\build\make-install\bin\*.lib

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: sdk/build/make-install/bin/
      