name: Get SDK binaries

on: 
  push: 
    branches: [dev]
  workflow_dispatch:


jobs:
  build_sdk:
    runs-on: windows-latest
    steps:
    - name: Checkout SDK
      uses: actions/checkout@v4
      with: 
        repository: 3DiVi/open-source-face-sdk
        ref: main

    - name: Setup
      run: |
          pip install gdown
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install wget

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build SDK
      run: |
          Add-Content sdk\scripts\windows\make_project.ps1 "msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj"
          cd sdk && .\scripts\windows\make_project.ps1

    - name: Clean
      run: |
          Remove-Item sdk\build\make-install\bin\*.exe
          Remove-Item sdk\build\make-install\bin\*.py
          Remove-Item sdk\build\make-install\bin\*.lib

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: sdk/build/make-install/bin/
      